kind: PersistentVolume
apiVersion: v1
metadata:
  name: iaworksheet-redis-dev-pv
spec:
  capacity:
    storage: 2Gi
  nfs:
    server: usmiabh1dnfs10a.vwoa.na.vwg
    path: /redis/dev/iaworksheet/iaworksheet-dev-redis-standalone/
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: iaworksheet-dev
    name: iaworksheet-redis-redis-standalone-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: non-dynamic
  volumeMode: Filesystem
